### PR TITLE
Choose transmitted contacts

### PR DESCRIPTION
**Pull request by ghost**
### First time contributor checklist
- [x] I have read [how to contribute](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [ ] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)
### Contributor checklist
- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
  - Device A, Android 6.0.1
- [x] My contribution is fully baked and ready to be merged as is
- [ ] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in my commit message

---
### Description

This allows choosing the contacts which should be sent to the server as contact list to increase privacy

### CODE REVIEW

**Comment by SecUpwN** [comment]
Welcome to `LibreSignal` and thanks for your pull request, @PrivacyPlus! I've taken a quick look on what you changed, looks good so far. before merging it, I'd like @mimi89999 to have a close look as well.

**Comment by mimi89999** [comment]
@PrivacyPlus Thanks for your PR and sorry for waiting so long before writing a reply. I tested it on my phone and it looks really good. I only have 2 remarks:
-- Could you please squash your commits?
-- The text `This increases privacy` doesn't really explain what this setting does.

**Comment by ghost** [comment]
@mimi89999 Should I merge everything into one commit?

**Comment by mimi89999** [comment]
@PrivacyPlus Yes please.

**Comment by ghost** [comment]
@mimi89999 Now it's only one commit.

**Comment by vanitasvitae** [comment]
Great feature!

**Pull request merged**
